以下の行列に対して、特異値分解をしてください。

In [3]:
import numpy as np
import scipy as sp

In [4]:
B = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
B

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [5]:
U, s, Vs = sp.linalg.svd(B)

In [6]:
U

array([[-0.14087668, -0.82471435,  0.53999635, -0.09167299],
       [-0.34394629, -0.42626394, -0.65166613,  0.52472017],
       [-0.54701591, -0.02781353, -0.31665681, -0.77442137],
       [-0.75008553,  0.37063688,  0.42832658,  0.34137419]])

In [7]:
s

array([2.54624074e+01, 1.29066168e+00, 2.40694596e-15])

In [8]:
Vs

array([[-0.50453315, -0.5745157 , -0.64449826],
       [ 0.76077568,  0.05714052, -0.64649464],
       [-0.40824829,  0.81649658, -0.40824829]])