以下の行列に対して、LU分解をして、Ax=bの方程式を解いてください。

In [3]:
import numpy as np
import scipy as sp

In [4]:
# データの準備
A = np.identity(3)
print(A)
A[0,:] = 1
A[:,0] = 1
A[0,0] = 3
b = np.ones(3)
print(A)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[3. 1. 1.]
 [1. 1. 0.]
 [1. 0. 1.]]
[1. 1. 1.]


In [6]:

# 正方行列を LU 分解する
(LU,piv) = sp.linalg.lu_factor(A)
L = np.identity(3) + np.tril(LU,-1)
U = np.triu(LU)
P = np.identity(3)[piv]
# 解を求める
x = sp.linalg.lu_solve((LU,piv),b)
x

array([-1.,  2.,  2.])

In [7]:
A@x

array([1., 1., 1.])

In [8]:
np.linalg.inv(A)@b

array([-1.,  2.,  2.])