要素がすべて3の5行5列の行列を作成し、その行列の2乗をする計算をしてみましょう。

In [2]:
import numpy as np

In [5]:
Matrix = np.ones((5, 5)) * 3

In [7]:
print(Matrix @ Matrix)

[[45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]]


In [8]:
print(np.dot(Matrix, Matrix))

[[45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]]
